// <auto-generated>
// Rewired Constants
// This list was generated on 19/06/2021 11:08:10
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "ThrustX")]
        public const int ThrustX = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "ThrustY")]
        public const int ThrustY = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "ShootX")]
        public const int ShootX = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "ShootY")]
        public const int ShootY = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Thrust")]
        public const int Thrust = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Shoot")]
        public const int Shoot = 3;
    }
    public static partial class Category {
        public const int Default = 0;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
